# Generated by Django 4.0.4 on 2022-06-16 14:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_branch', models.CharField(max_length=30)),
                ('description_of_branch', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('content_of_feedback', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Frieght_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Logistics_solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_offer', models.CharField(max_length=30)),
                ('description_of_offer', models.TextField(max_length=300)),
                ('image_of_offer', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=30)),
                ('description_of_service', models.TextField(max_length=300)),
                ('image_for_service', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Why_choose_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descriptions', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('departureCity', models.CharField(max_length=30)),
                ('deliveryCite', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('length', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('fragile', models.BooleanField()),
                ('expressDelivery', models.BooleanField()),
                ('insurance', models.BooleanField()),
                ('packaging', models.BooleanField()),
                ('code', models.CharField(max_length=6, null=True, unique=True)),
                ('official_Code', models.CharField(max_length=300, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('freightType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalHub.frieght_type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_email', models.EmailField(max_length=254)),
                ('order_info', models.TextField(max_length=300)),
                ('official_code', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalHub.branch')),
            ],
        ),
    ]
