# Generated by Django 4.0.4 on 2022-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalHub', '0002_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_for_service',
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.TextField(default='globalHub/assets/images/Aireplane.svg'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_of_service',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_of_service',
            field=models.CharField(max_length=40),
        ),
    ]
