# Generated by Django 4.0.4 on 2022-05-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalHub', '0002_about_us_contact_us_logistics_solution_why_choose_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
