# Generated by Django 4.0.4 on 2022-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalHub', '0003_remove_service_image_for_service_service_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_url',
            field=models.TextField(default='globalHub/assets/images/Aireplane.svg'),
        ),
    ]
