# Generated by Django 4.0.4 on 2022-06-14 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globalHub', '0004_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oficial_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subject',
        ),
        migrations.AddField(
            model_name='order',
            name='official_code',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='code',
            field=models.TextField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='official_Code',
            field=models.TextField(default='', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
