# Generated by Django 4.0.4 on 2022-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalHub', '0005_remove_order_oficial_code_remove_order_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
