# Generated by Django 4.0.4 on 2022-07-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalHub', '0008_alter_contact_us_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='code',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='official_Code',
        ),
    ]
